spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fintrack_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:maksimlych}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:227622}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

jwt.secret=${JWT_SECRET:SGVsbG9UaGlzSXNBVmVyeUxvbmczMlN0cmluZ0Jhc2U2NEVuY29kZWRLZXlGb3JKV1Q=}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=${SERVER_PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.liquibase=INFO